# Ördin Default Parameters
# Author: Jimmy Moses (jimmy.moses@pnguot.ac.pg)
# Default parameter values for all analyses

# Ordination defaults
NMDS_DEFAULT_K <- 2
NMDS_DEFAULT_TRYMAX <- 20
NMDS_DEFAULT_DISTANCE <- "bray"
NMDS_DEFAULT_PERMUTATIONS <- 999

PCA_DEFAULT_SCALING <- 2

CA_DEFAULT_SCALING <- 2

DCA_DEFAULT_IRMINS <- 0

PCOA_DEFAULT_K <- 2
PCOA_DEFAULT_DISTANCE <- "bray"

# Constrained ordination
CCA_DEFAULT_SCALING <- 2
CCA_DEFAULT_PERMUTATIONS <- 999

RDA_DEFAULT_SCALING <- 2
RDA_DEFAULT_PERMUTATIONS <- 999

DBRDA_DEFAULT_DISTANCE <- "bray"
DBRDA_DEFAULT_PERMUTATIONS <- 999

CAP_DEFAULT_DISTANCE <- "bray"
CAP_DEFAULT_PERMUTATIONS <- 999

# Statistical tests
PERMANOVA_DEFAULT_PERMUTATIONS <- 999
PERMANOVA_DEFAULT_DISTANCE <- "bray"

ANOSIM_DEFAULT_PERMUTATIONS <- 999
ANOSIM_DEFAULT_DISTANCE <- "bray"

MANTEL_DEFAULT_PERMUTATIONS <- 999

ENVFIT_DEFAULT_PERMUTATIONS <- 999

# Diversity analysis
INEXT_DEFAULT_KNOTS <- 40
INEXT_MIN_KNOTS <- 20
INEXT_MAX_KNOTS <- 100
INEXT_DEFAULT_CONF <- 0.95
INEXT_DEFAULT_DATATYPE <- "abundance"

# Plot defaults
PLOT_DEFAULT_DPI <- 300
PLOT_DEFAULT_WIDTH <- 8
PLOT_DEFAULT_HEIGHT <- 6
PLOT_DEFAULT_FORMAT <- "png"
PLOT_DEFAULT_THEME <- "bw"
PLOT_DEFAULT_FONT <- "sans"
PLOT_DEFAULT_BASE_SIZE <- 12
PLOT_DEFAULT_TITLE_SIZE <- 14
PLOT_DEFAULT_POINT_SIZE <- 2
PLOT_DEFAULT_POINT_SHAPE <- 21
PLOT_DEFAULT_POINT_COLOR <- "#2e8b57"
PLOT_DEFAULT_LINE_WIDTH <- 1.5
PLOT_DEFAULT_AXIS_WIDTH <- 1

# Data validation
MAX_UPLOAD_SIZE_MB <- 50
MIN_SITES <- 3
MIN_SPECIES <- 2
